### ISSUE TITLE
Debug does not redirect output to logger when used in a TS project

### ISSUE THREAD

**Issue by kamatheuska** [pinojs/pino-debug#125]
I am currently on a TS project in a project type CommonJS with fastify. The compiled version looks like this:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const pinoDebug = require("pino-debug");
const pino_1 = require("pino");
const myLogger = (0, pino_1.default)({
    level: 'debug',
});
pinoDebug(myLogger, {
    map: {
        'app:info:*': 'info',
        'app:*': 'debug',
        '*': 'trace',
    },
});
```

Still, I am getting pretty-printed logs (unredirected output) when using `debug`, while myLogger is the one in JSON format:

```bash
app:info:plugins:env Start connection to MongoDB +0ms
{"level":50,"time":1672309093991,"pid":78147,"hostname":"kameush-home","err":{"type":"FastifyError","message":"fastify-plugin: Plugin did not start in time: 'app'. You may have forgotten to call 'done' function or to resolve a Promise: Plugin did not start in time: 'app'. You may have forgotten to call 'done' function or to resolve a Promise","stack":"FastifyError: fastify-plugin: Plugin did not start in time: 'app'. You may have forgotten to call 'done' function or to resolve a Promise\n    at manageErr (/home/nicolas/Projects/inventory-app/app/node_modules/fastify/fastify.js:542:33)\n 
```

Is there a workaround to use this module with Typescript?

Example in  the `example` folder seems to run just fine.

**Comment by Ognian** [comment]
I had the same problem; When debugging this I found that on this line: https://github.com/pinojs/pino-debug/blob/c9175627c1a94dd24b4d88b404f406075cd77a73/index.js#L26 debug.logger is overridden by the Pino logger BUT `debug.log` should be overwritten...
Since I have absolutely no time to research why this happens (has the debug lib changed something or whatever ) I quickly dirty patched it that way in my code:
```js
// Fix bug
debug.log = (...args) => {
  // Route debug output through Pino
  logger.info(args.join(' '))
}
```
this works as long as the level mention in logger (logger.info) matches what you have enabled via map...

**Comment by kamatheuska** [comment]
Actually I don't use this module anymore, I just patch debug myself with pino. Makes more sense where I have implemented it

**Comment by FoxxMD** [comment]
@kamatheuska can you elaborate on how you are patching debug? I'm also using TS and would like pino-debug functionality but its turning out to be difficult to use.
