### ISSUE TITLE
Publish ES5 version / bundle to npm.

### ISSUE THREAD

**Issue by smeijer** [pinojs/pino-debug#19]
Adding this library to a meteor project prevents it from building.

It only throws a syntax error, without specific details. But that's more a problem of Meteor / Uglifyjs.

I've managed to locate the error by trial and error, and reduced it to the removal of a simple `import debug from 'pino-debug'`.

```
SyntaxError: Unexpected character '`'
```

I guess it's because this project uses template literals, which gave me some troubles before. I expect that publishing a "precompiled" version to NPM will fix this issue. Having a "precompiled" version would be nice anyway, so older node/browser versions are supported as well.

https://github.com/pinojs/pino-debug/blob/f3f398db33ad483e20d477da5298541f85937f40/index.js#L62

**Comment by davidmarkclements** [comment]
we tend to stay away from precompiling dependencies and instead keep the syntax of pino ecosystem modules aligned with the common syntax of the Maintence release lines of Node.js

Template literals have been in the language since 2015, and are supported in Node 4 upwards. 
Node 4 is about to reach end of life, and Node 10 will shortly be released. So by the end of April template literals will have been in 4 generations of Node.js.

This seems to be a problem with UglifyJS - in which case I would recommend switching to another minifier.

An alternative would be to transpile the dependency in your tree, this can be achieved with both browserify and webpack (I think).

**Comment by davidmarkclements** [comment]
closing for now as a "wontfix" but please feel free to keep discussing

**Comment by smeijer** [comment]
> in which case I would recommend switching to another minifier.

Unfortunately, with Meteor that's not so easy as it sounds.

> this can be achieved with both browserify and webpack (I think).

Again, not with Meteor. 😞 

---

But I understand your point of view. Thanks for the quick response.

Pino and Pino-Noir are working just fine BTW :) Thanks for your awesome work.
